# SMS with Python using twilio api. Using python we can receive text message on our phone.
# Copy code from twilio site and paste it here. Get auth_token from twilio dashboard after login and
# add here for auth_token variable and also add text message on body variable.

from twilio.rest import Client

account_sid = ' '  # will be generated by twilio
auth_token = ' '  # get auth_token from twilio dashboard after login.

client = Client(account_sid, auth_token)

message = client.messages.create(
    # from_='<enter sender number>',  # trial number generated by twilio
    body='Hello my third sms from sms.py file using twilio api',  # add text message
    # to='<enter receiver number>'
)

print(message.sid)
